[workspace]
resolver = "2"
members = [
    "crates/wgpy",
    "crates/wgpy_core",
    "crates/wgpy_math",
    "crates/test_utils",
    "crates/wgpy_pyo3",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
pyo3 = { version = "0.20.2", features = ["extension-module"] }
#arrow_gpu = { path="../arrow-gpu/crates/arrow"}
arrow_gpu = { git="https://github.com/psvri/arrow-gpu.git", rev = "c5874d0e2c56ed3023f489b50c2dc3860ba40799"}
wgpu = "0.19.0"
once_cell = "1.18.0"
bytemuck = "1.14.0"

[profile.release]
debug=1