[workspace]
resolver = "2"
members = [
    "crates/wgpy",
    "crates/wgpy_core",
    "crates/wgpy_pyo3",
    "crates/wgpy_math",
    "crates/test_utils"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }
#arrow_gpu = { path="../arrow-gpu/crates/arrow"}
arrow_gpu = { git="https://github.com/psvri/arrow-gpu.git", rev = "82caa99a3ad792085e90c3084defef418ce3df21"}
pollster = "0.3.0"
futures = "0.3.29"
wgpu = "0.18.0"
once_cell = "1.18.0"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }

[profile.release]
debug=1