[workspace]
resolver = "2"
members = [
    "crates/wgpy",
    "crates/wgpy_core",
    "crates/wgpy_math",
    "crates/test_utils",
    "crates/wgpy_pyo3",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
pyo3 = { version = "0.20.2", features = ["extension-module"] }
#arrow_gpu = { path="../arrow-gpu/crates/arrow"}
arrow_gpu = { git="https://github.com/psvri/arrow-gpu.git", rev = "f0133a4199bccb5681b91f61fc92ad29ef50e77d"}
wgpu = "0.19.1"
once_cell = "1.19.0"
bytemuck = "1.14.3"

[profile.release]
debug=1