codecov:
  notify:
    after_n_builds: 1

github_checks: false

comment:
  layout: "header, files, footer"
  require_head: false
  require_base: false
  require_changes: false
  hide_project_coverage: false
