[package]
name = "webgpupy_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow_gpu = {workspace=true}
wgpu = {workspace=true}